version: '3.4'

services:
    
  catologdb:
    image: mongo

  catolog.api:
    image: ${DOCKER_REGISTRY-}catologapi
    build:
      context: .
      dockerfile: Services/Catolog/Catolog.API/Dockerfile

volumes:
  mongo_data:
